### ISSUE TITLE
Networking - Ability to filter NOT INCLUDED IN

### ISSUE THREAD

**Issue by stylescube** [stylescube/Sam-s-Custodian#10]
We have a list of valid IP addresses. We want to find a list of resources that are not in the set of approved IP lists. This is where the need for Not In or Not Included In comes in.

**Comment by stefangordon** [comment]
linking to https://github.com/cloud-custodian/cloud-custodian/issues/4395

**Comment by stefangordon** [comment]
This should be in shortly https://github.com/cloud-custodian/cloud-custodian/pull/4431

**Comment by stefangordon** [comment]
Firewall filters now have `any` and `only`.  This case specifically called for `only` as in it will return True if `only` the IPs you provide are found in the firewall.   You can prefix the filter with `not` to find firewalls that have IP's not included in the `only` list.
